# Generated by Django 3.2.13 on 2022-06-30 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20220630_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 10, 58, 41, 862141, tzinfo=utc)),
        ),
    ]
