# Generated by Django 3.2.14 on 2022-07-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
