# Generated by Django 3.2.14 on 2022-07-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
